version: '3.9'
volumes:
  elasticsearch_data: {}
  excel_data: {}

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ES_URL: http://elasticsearch:9200
      NEXT_BASE_PATH: /jurisprudencia
    ports:
      - "3000:3000"
    volumes:
      - excel_data:/usr/src/app/files
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - prod
  server-dev:
    build:
      context: .
      dockerfile: ./Dockerfile_dev
    environment:
      ES_URL: http://elasticsearch:9200
      NEXT_BASE_PATH: /dev-jurisprudencia
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - excel_data:/usr/src/app/files
      - .:/usr/src/app
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - dev
  clitools:
    build:
      context: ./compose/clitools
    environment:
      ES_URL: http://elasticsearch:9200
      ES_USER: elastic
      ES_PASS: elasticsearch
    profiles:
      - dev
      - prod
  elasticsearch:
    build:
      context: ./compose/elasticsearch
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      xpack.security.enabled: true
      xpack.security.http.ssl.enabled: false
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms6g -Xmx6g
      ELASTIC_PASSWORD: elasticsearch
      # to use kibana set the kibana_system password to elasticsearch with:
      # $ elasticsearch-reset-password -u kibana_system -i
    healthcheck:
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://elastic:elasticsearch@localhost:9200
      interval: 10s
      timeout: 30s
      retries: 15
      start_period: 10s
    restart: unless-stopped
    profiles:
      - prod
      - dev
      - kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.0
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: elasticsearch
    restart: always
    profiles:
      - kibana
