version: '3.9'
volumes:
  elasticsearch_data: {}

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ES_URL: http://elasticsearch:9200
    ports:
      - "80:3000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

  elasticsearch:
    build:
      context: ./compose/elasticsearch
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
    healthcheck:
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200
      interval: 10s
      timeout: 30s
      retries: 15
      start_period: 10s
    restart: unless-stopped
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.0
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    restart: always
